// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANm0SdEcl7gi-wp4bCYXkBO7KW4DshQIw',
    appId: '1:286595756668:web:a7b4a34dcdc033daf78ff9',
    messagingSenderId: '286595756668',
    projectId: 'foxcare-31d8d',
    authDomain: 'foxcare-31d8d.firebaseapp.com',
    storageBucket: 'foxcare-31d8d.appspot.com',
    measurementId: 'G-70S8NWQWL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7e04KYpN8bFHdbXMbKCKcdh5g3oepZzA',
    appId: '1:286595756668:android:ad3b133e28bd038cf78ff9',
    messagingSenderId: '286595756668',
    projectId: 'foxcare-31d8d',
    storageBucket: 'foxcare-31d8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDq479-qnfS7yhd2Z7yzglI5oxRAl3Ys',
    appId: '1:286595756668:ios:68faef7cf2e9488bf78ff9',
    messagingSenderId: '286595756668',
    projectId: 'foxcare-31d8d',
    storageBucket: 'foxcare-31d8d.appspot.com',
    iosBundleId: 'com.foxcare.foxcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvDq479-qnfS7yhd2Z7yzglI5oxRAl3Ys',
    appId: '1:286595756668:ios:68faef7cf2e9488bf78ff9',
    messagingSenderId: '286595756668',
    projectId: 'foxcare-31d8d',
    storageBucket: 'foxcare-31d8d.appspot.com',
    iosBundleId: 'com.foxcare.foxcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANm0SdEcl7gi-wp4bCYXkBO7KW4DshQIw',
    appId: '1:286595756668:web:a3787ec5dd7dac2af78ff9',
    messagingSenderId: '286595756668',
    projectId: 'foxcare-31d8d',
    authDomain: 'foxcare-31d8d.firebaseapp.com',
    storageBucket: 'foxcare-31d8d.appspot.com',
    measurementId: 'G-WVTRR0XB9G',
  );
}
